### ISSUE TITLE
how to use ollama(Locally)

### ISSUE THREAD

**Issue by samansayar** [upstash/rag-chat#39]
I need guidance on how to integrate Ollama with my existing project.

How can I work with Ollama in this project?

**Comment by ogzhanolguncu** [comment]
I'm not exactly sure how to do it with Ollama, but if you can get a `apiKey` and `baseUrl` can you do the following:

```ts
export const ragChat = new RAGChat({
  model: custom("codellama/CodeLlama-70b-Instruct-hf", {
    apiKey: "YOUR_FAKE_API_KEY",
    baseUrl: "YOUR_ENDPOINT",
  }),
});
```

**Comment by enesakar** [comment]
yes ollama is openai compatible. https://ollama.com/blog/openai-compatibility

let us know if you need further help.
