### ISSUE TITLE
Possible integration for Anthropic LLMs

### ISSUE THREAD

**Issue by umutbozdag** [upstash/rag-chat#59]
I see that currently Anthropic LLMs are not supported. Do you guys have a plan to implement it in the future?

**Comment by ogzhanolguncu** [comment]
Yes. Possibly using `AnthropicChat` from `langchain` to make integration easier. Feel free to send a PR.

**Comment by umutbozdag** [comment]
Can you please check #60 @ogzhanolguncu

**Comment by yunusemreozdemir** [comment]
Closing this issue as this integration is implemented in PR [#64](https://github.com/upstash/rag-chat/pull/64), [#67](https://github.com/upstash/rag-chat/pull/67) and released in [v1.5.0](https://github.com/upstash/rag-chat/releases/tag/v1.5.0).
