### ISSUE TITLE
llamaindex version not updated

### ISSUE THREAD

**Issue by mrsamirr** [upstash/rag-chat#82]
installed the latest version, still not find updated llamaindex
![image](https://github.com/user-attachments/assets/047227eb-6c64-43c3-a3de-5a60fbf77542)

**Comment by ytkimirti** [comment]
We had issues with llamaindex's versions so we fixed it's version to 0.5.24 for now. I will try it with the latest version today and if it's ok, we will make a new release

**Comment by mrsamirr** [comment]
thats good @ytkimirti , because getting error on vercel deployment [issue](https://github.com/run-llama/create-llama/issues/164)

**Comment by ytkimirti** [comment]
Oh I didn't know this was caused by llamaindex, thanks!

**Comment by CahidArda** [comment]
We removed llamaindex from our dependencies as it was causing errors @mrsamirr

**Comment by mrsamirr** [comment]
why not updated llamaindex version to 0.6.2,
as it was [mentioned](https://github.com/run-llama/create-llama/issues/164#issuecomment-2388291446) 

the llamaindex 0.5.24 causing errors

**Comment by CahidArda** [comment]
we are closing the issue as we dropped support for llamaindex.
